#pac codepipeline src build yaml
version: 0.2
env:
  shell: bash
phases:
  pre_build:
    commands:
      - java -version
      - gradle -v
      - ls -lrt
      - ls /home/test/pac-app/
      - chmod 777 -R *
  build:
    commands:
      - gradle build --no-daemon
      - ./build-native-image.sh
      - chmod 755 bootstrap
      - chmod 755 server
      - mkdir -p res
      - cp bootstrap libsunec.so cacerts server template.yaml /home/test/pac-app/
      - rm -rf *
      - cp /home/test/pac-app/* ./
      - more template.yaml
      - aws cloudformation package --template-file template.yaml --output-template-file packaged-template.yaml --s3-bucket csvs3lambda2
      - more packaged-template.yaml
      - aws cloudformation create-change-set --stack-name pac-batch-springnative-stack --change-set-name ChangeSetPAC --template-body file://packaged-template.yaml --capabilities CAPABILITY_IAM
      - pwd
  post_build:
    commands:
      - aws cloudformation wait change-set-create-complete --stack-name pac-batch-springnative-stack --change-set-name ChangeSetPAC
      - aws cloudformation execute-change-set --change-set-name ChangeSetPAC --stack-name pac-batch-springnative-stack
artifacts:
  files:
    - template.yaml
    - packaged-template.yaml
  discard-paths: yes
