AWSTemplateFormatVersion : '2010-09-09'
Description: Import Lambda
Resources:
  LambdaResource:
    Type: AWS::Lambda::Function
    DeletionPolicy: Retain
    Properties:
      FunctionName: pac-batch-springnative
      Role: arn:aws:iam::023174938363:role/pac-batch-springboot-role
      Runtime: provided.al2
      Handler: function.handler
      Code: ./
